/*
 * A secret is compared whole, or nobody can log in.
 *
 * `API_TOKEN` was being run through `normalizeOptionalText(value, 512)` — a normalizer for
 * text that gets DISPLAYED, which truncates. On a secret that is compared, truncation is
 * wrong in both directions at once:
 *
 *   an API_TOKEN longer than 512 characters LOCKED THE OPERATOR OUT of every requireBearer
 *   route, because the expected value was cut to 512 while the presented bearer was not.
 *   No credential worked — not the correct one, not any.
 *
 *   and a 512-character PREFIX of the real token was ACCEPTED, capping the effective secret
 *   at 512 characters no matter what was configured.
 *
 * Both are silent. Nothing throws, nothing logs, and the operator's only symptom is 403 on
 * a token they can see is correct.
 *
 * The storage-adapter half of this sweep lives in tests/backend-storage-adapter.test.js,
 * beside the other cases for that module.
 */

import { describe, expect, test } from 'vitest';
import { hasApiTokenAccess, resolveAgentTokenMode } from '../lib/backend/auth-adapter.js';

const bearer = (token) => ({ headers: { authorization: `Bearer ${token}` } });

describe('a secret is compared whole', () => {
  test('an API_TOKEN longer than 512 characters still authenticates', () => {
    /*
     * The lockout, as the operator would meet it: a token generated by something that does
     * not cap length (a JWT, `openssl rand -base64 512`), pasted correctly into both .env
     * and the client, rejected on every requireBearer route with no credential that works.
     */
    const token = `hf_${'x'.repeat(600)}`;
    expect(hasApiTokenAccess(bearer(token), { env: { API_TOKEN: token } })).toBe(true);
  });

  test('a 512-character prefix of the real token is refused', () => {
    /*
     * The same bug in the dangerous direction, and the reason the fix is not "raise the
     * cap": truncating the EXPECTED value made any correct prefix pass, so the effective
     * secret was capped at 512 characters no matter what was configured. An attacker who
     * learned a prefix held a working credential.
     */
    const token = `hf_${'x'.repeat(600)}`;
    expect(hasApiTokenAccess(bearer(token.slice(0, 512)), { env: { API_TOKEN: token } })).toBe(false);
    expect(hasApiTokenAccess(bearer(token.slice(0, 100)), { env: { API_TOKEN: token } })).toBe(false);
  });

  test('ordinary tokens are unaffected, including surrounding whitespace in .env', () => {
    expect(hasApiTokenAccess(bearer('short-token'), { env: { API_TOKEN: 'short-token' } })).toBe(true);
    // Trimming is kept; a trailing newline from a heredoc must not lock anyone out either.
    expect(hasApiTokenAccess(bearer('short-token'), { env: { API_TOKEN: '  short-token\n' } })).toBe(true);
    expect(hasApiTokenAccess(bearer('wrong'), { env: { API_TOKEN: 'short-token' } })).toBe(false);
  });

  test('token length does not steer the resolved auth mode', () => {
    /*
     * The same truncated value also fed the "is a bearer configured at all" decision inside
     * resolveAgentTokenMode. Truncating a 600-char token still left a truthy 512-char
     * string, so that path happened to survive — but only by accident of the cap being
     * shorter than the token, and this pins that length is not an input to the decision.
     */
    const short = resolveAgentTokenMode({ API_TOKEN: 'abc' });
    const long = resolveAgentTokenMode({ API_TOKEN: 'x'.repeat(600) });
    expect(long).toEqual(short);
  });

  test('an empty or absent token grants nothing', () => {
    for (const value of [undefined, '', '   ', null]) {
      expect(hasApiTokenAccess(bearer('anything'), { env: { API_TOKEN: value } }), String(value))
        .toBe(false);
    }
  });
});
