/*
 * Seed a throwaway hafleet backend for live UX validation.
 *
 * WHY THIS IS A SCRIPT AND NOT A FEW CURL LINES. Two reasons, both learned the
 * hard way in one sitting:
 *
 * 1. THE SEED MUST NOT LOOK LIKE THE FIXTURE. The first version of this seed used
 *    the fixture's own agent names, so `every live agent name appears on the page`
 *    passed while the page was showing pure fixture data and the provenance banner
 *    was absent. An assertion that cannot distinguish its two possible sources
 *    tests nothing. Every name and preset here is chosen to appear NOWHERE in
 *    lib/mock-data.js, and scripts/live-ux.mjs additionally asserts that no
 *    fixture-only value is on screen.
 *
 * 2. A PARTIAL WIPE LEAVES A DIRTY ORACLE. The second run failed the guard because
 *    the alert store still held alerts naming agents from an earlier seed. Alerts
 *    are generated by the liveness sweep, so they outlive the agents that caused
 *    them. This script clears every persisted store, not just the two it writes.
 *
 * It talks to the backend over HTTP rather than writing data/ files directly, so
 * the registration path — preset resolution into a runtimeProfile included — is
 * exercised rather than bypassed.
 *
 * Run:  node scripts/seed-live.mjs
 *       RUNTIME=/path/to/runtime node scripts/seed-live.mjs
 */

import { rmSync, mkdirSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const BACKEND = process.env.BACKEND ?? 'http://127.0.0.1:8090';
const TOKEN = process.env.API_TOKEN ?? 'devtoken';
const RUNTIME = process.env.RUNTIME ?? '';

async function call(path, body, method) {
  const res = await fetch(`${BACKEND}/api/${path}`, {
    method: method ?? (body ? 'POST' : 'GET'),
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${TOKEN}` },
    body: body ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`${path} -> ${res.status} ${text.slice(0, 200)}`);
  return text ? JSON.parse(text) : null;
}

/*
 * Deliberately unlike the fixture: `lend-*` names, and a model mix that differs
 * from it too (Sonnet and Fable rather than Opus, Codex at high rather than
 * medium). The models still come from lib/role-capacity.json, because tier
 * matching is one of the things under test.
 */
const PRESETS = [
  { name: 'Lend A — Sonnet', framework: 'claude', provider: 'anthropic', model: 'claude-sonnet-5' },
  { name: 'Lend B — Kimi', framework: 'octos', provider: 'moonshot', model: 'kimi-k3' },
  { name: 'Lend C — Codex high', framework: 'codex', provider: 'openai', model: 'gpt-5.6-sol', reasoning: 'high' },
  { name: 'Lend D — Fable', framework: 'claude', provider: 'anthropic', model: 'claude-fable-5' },
];

const AGENTS = [
  { name: 'lend-sonnet-01', preset: 0, transport: 'tmux', tmux: 'lend-sonnet-01:0.0' },
  { name: 'lend-kimi-02', preset: 1, transport: 'acp', tmux: null },
  { name: 'lend-codex-03', preset: 2, transport: 'tmux', tmux: 'lend-codex-03:0.0' },
  { name: 'lend-fable-04', preset: 3, transport: 'acp', tmux: null },
  // No preset: registered, running, contributing nothing. The console has to
  // report that it qualifies for no role rather than assuming a default, and this
  // is the state every agent is in before a wizard exists.
  { name: 'lend-unconfigured-05', preset: null, transport: 'acp', tmux: null, type: 'codex-acp' },
];

function wipe() {
  if (!RUNTIME) {
    console.log('RUNTIME not set — skipping the wipe. Stores may hold prior data.');
    return;
  }
  const dir = join(RUNTIME, 'data');
  if (existsSync(dir)) {
    // Every store, not just the two this script writes: alerts outlive the agents
    // that produced them, so a partial wipe leaves stale names on screen and the
    // fixture guard fails for the wrong reason.
    for (const f of readdirSync(dir)) {
      if (f.endsWith('.json') || f.endsWith('.jsonl')) rmSync(join(dir, f), { force: true });
    }
  }
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'agents.json'), '{}');
  writeFileSync(join(dir, 'framework-presets.json'), '[]');
  console.log(`wiped ${dir}`);
}

if (process.argv.includes('--wipe-only')) { wipe(); process.exit(0); }

const ids = [];
for (const p of PRESETS) {
  // `ceiling` is sent on purpose and is expected to vanish: the POST handler
  // builds its record from a closed field list, so this is where the console's
  // "no ceiling field upstream" blank is proven rather than assumed.
  const r = await call('framework-presets', { ...p, ceiling: { tokens: 5_000_000, period: 'monthly' } });
  ids.push(r.preset.id);
  if (r.preset.ceiling !== undefined) {
    console.log(`  NOTE: ceiling now survives POST — the console's no-ceiling blank is stale`);
  }
}

for (const a of AGENTS) {
  const body = { name: a.name, transport: a.transport, tmux: a.tmux };
  if (a.preset !== null) body.presetId = ids[a.preset];
  if (a.type) body.type = a.type;
  await call('agents', body);
}

/*
 * Tasks, so the MEASURED half of /usage is not empty. Busy time comes from the
 * runtime sweep and will be zero here because these agents are registered rather
 * than running — which is itself the honest state to render.
 */
const TASKS = [
  ['lend-sonnet-01', 'Port the auth module'],
  ['lend-sonnet-01', 'Review the ACP handshake'],
  ['lend-kimi-02', 'Draft the migration plan'],
  ['lend-codex-03', 'Fix the flaky retry test'],
];
for (const [assignee, title] of TASKS) {
  await call('tasks', { title, assignee, creator: 'operator', priority: 'p2' });
}

/*
 * Engagements, and all three routing branches.
 *
 * A seed that only produced the happy path is how "falls back to approval" gets
 * built as "rejects" — the branch is never seen, so nothing contradicts a wrong
 * implementation. So: one whitelisted room inside the offer (auto-joins), one
 * whitelisted room over it (falls back), one room that is not whitelisted.
 *
 * The write suite consumes pending engagements by approving and rejecting them, so
 * there are deliberately more pending than it needs.
 */
const TRUSTED = '!aXbY7pQ2:hq.example';
const UNTRUSTED = '!zZ1qW3eR:hq.example';

await call('offers/architect', {
  count: 2, budgetCapPerEngagement: 1_000_000, rateCap: 60_000, published: true,
}, 'PUT');
await call('offers/coding', {
  count: 3, budgetCapPerEngagement: 800_000, rateCap: 50_000, published: true,
}, 'PUT');
await call('whitelist', {
  projectRoomId: TRUSTED, displayName: 'acme/api-service', addedBy: '@me:hq.example',
});

const REQUESTS = [
  // whitelisted and inside the offer -> auto-join
  [TRUSTED, 'acme/api-service', 'architect', 400_000],
  // whitelisted but over the offer cap -> falls back to approval, NOT rejected
  [TRUSTED, 'acme/api-service', 'architect', 2_000_000],
  // not whitelisted -> approval
  [UNTRUSTED, 'openssl/fips-review', 'coding', 300_000],
  // spare pending rows for the write suite to consume
  [UNTRUSTED, 'openssl/fips-review', 'coding', 120_000],
  [UNTRUSTED, 'gnu/coreutils-port', 'architect', 90_000],
];
for (const [room, project, role, tokens] of REQUESTS) {
  await call('engagements', {
    project, projectRoomId: room, role,
    requester: '@lin:hq.example', requestedTokens: tokens, ratePerDay: 20_000,
  });
}

const agents = await call('agents');
const presets = await call('framework-presets');
const engagements = (await call('engagements')).engagements;
const routes = engagements.reduce((acc, e) => {
  acc[e.route ?? 'autoJoin'] = (acc[e.route ?? 'autoJoin'] ?? 0) + 1;
  return acc;
}, {});
console.log(`\nengagements by route: ${JSON.stringify(routes)}`);
// Loud, because a seed that silently stopped exercising a branch would let the
// suite go on passing over a routing bug.
for (const want of ['autoJoin', 'overOffer', 'notWhitelisted']) {
  if (!routes[want]) console.log(`  WARNING: no engagement took the ${want} branch`);
}
console.log(`\nseeded ${presets.length} presets, ${agents.length} agents against ${BACKEND}`);
for (const a of agents) {
  const m = a.runtimeProfile?.primary?.model ?? '—';
  console.log(`  ${a.name.padEnd(22)} ${String(a.type).padEnd(11)} ${m.padEnd(18)} preset=${a.presetId ?? 'null'}`);
}
console.log(`\nceiling survived POST: ${presets.some((p) => p.ceiling !== undefined)}`);
